#!/bin/bash

STAGE=$1

if [ -z "$STAGE" ];
then
    echo "Usage: $0 STAGE"
    exit 1
fi

DIR=`dirname $0`

cp $DIR/$STAGE/en.item.template ../$DIR/en/item.template
cp $DIR/$STAGE/ru.item.template ../$DIR/ru/item.template
